//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELOCBS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RELOCBS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BTR_Dest_Format {
            get {
                object obj = ResourceManager.GetObject("BTR_Dest_Format", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BTR_Origin_Format {
            get {
                object obj = ResourceManager.GetObject("BTR_Origin_Format", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CityCostFormat {
            get {
                object obj = ResourceManager.GetObject("CityCostFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CurrencyConversionFormat {
            get {
                object obj = ResourceManager.GetObject("CurrencyConversionFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Destination_BGRS_AIR {
            get {
                object obj = ResourceManager.GetObject("Destination_BGRS_AIR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Destination_BGRS_BTR {
            get {
                object obj = ResourceManager.GetObject("Destination_BGRS_BTR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Destination_BGRS_SEA {
            get {
                object obj = ResourceManager.GetObject("Destination_BGRS_SEA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DestinationCostUploadFormat {
            get {
                object obj = ResourceManager.GetObject("DestinationCostUploadFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Freight_BGRS_AIR {
            get {
                object obj = ResourceManager.GetObject("Freight_BGRS_AIR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Freight_BGRS_BTR {
            get {
                object obj = ResourceManager.GetObject("Freight_BGRS_BTR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Freight_BGRS_SEA {
            get {
                object obj = ResourceManager.GetObject("Freight_BGRS_SEA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FreightCostUploadFormat {
            get {
                object obj = ResourceManager.GetObject("FreightCostUploadFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GDPR_DataSubject_Consent_Form {
            get {
                object obj = ResourceManager.GetObject("GDPR_DataSubject_Consent_Form", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GDPR_Privacy_Policy_V1 {
            get {
                object obj = ResourceManager.GetObject("GDPR_Privacy_Policy_V1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Origin_BGRS_AIR {
            get {
                object obj = ResourceManager.GetObject("Origin_BGRS_AIR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Origin_BGRS_BTR {
            get {
                object obj = ResourceManager.GetObject("Origin_BGRS_BTR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Origin_BGRS_SEA {
            get {
                object obj = ResourceManager.GetObject("Origin_BGRS_SEA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OriginCostUploadFormat {
            get {
                object obj = ResourceManager.GetObject("OriginCostUploadFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ROADCostUploadFormat {
            get {
                object obj = ResourceManager.GetObject("ROADCostUploadFormat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\Nikhil\RELOCBS.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TransferToFA {
            get {
                object obj = ResourceManager.GetObject("TransferToFA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TransferToFAReloSmart {
            get {
                object obj = ResourceManager.GetObject("TransferToFAReloSmart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TransferToFAReloTrack {
            get {
                object obj = ResourceManager.GetObject("TransferToFAReloTrack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnExpected error occured At BL.
        /// </summary>
        internal static string UnExpectedErrorAtBL {
            get {
                return ResourceManager.GetString("UnExpectedErrorAtBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnExpected error occured At DAL.
        /// </summary>
        internal static string UnExpectedErrorAtDAL {
            get {
                return ResourceManager.GetString("UnExpectedErrorAtDAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnExpected error occured.Please contact IT team.
        /// </summary>
        internal static string UnExpectedErrorAtPL {
            get {
                return ResourceManager.GetString("UnExpectedErrorAtPL", resourceCulture);
            }
        }
    }
}
